export enum MenuItemCategories {
  ALL = "ALL",
  HOT_COFFEES = "HOT COFFEES",
  COLD_COFFEES = "COLD COFFEES",
  MILKSHAKES = "MILKSHAKES",
  SMOOTHIES = "SMOOTHIES",
  LUNCH = "LUNCH",
  MERCHANDISE = "MERCHANDISE",
}
