export enum MenuItemCategories {
  ALL = "ALL",
  DEALS = "DEALS",
  HOT_DRINKS = "HOT DRINKS",
  COLD_DRINKS = "COLD DRINKS",
  MILKSHAKES = "MILKSHAKES",
  SMOOTHIES = "SMOOTHIES",
  LUNCH = "LUNCH",
  MERCHANDISE = "MERCHANDISE",
}
